workflows:
  android-workflow:
    name: Android Cordova workflow
    instance_type: mac_pro
    environment:
      vars:
        BUILD_NUMBER: "$PROJECT_BUILD_NUMBER+10000"
        KEYSTORE: Encrypted(Z0FBQUFBQmcwZEF2UHF5Wm4yNmlhWGRUaUVDZVQ1M2cxbC1JUzgybWE4SWI1dDloaDJwaXlLUS1zYVFUYWo5U0lQZ3ExLXh3LXpvcGZ5QkdsdE01Smh2akt2R0pZRVdpRXB3ekthODNseVhWYnZhZ0RjZWtMLWZmZ3V6Smt4Y1cxa0w5UHE5Zm0zWWtUT0hmOGkyYXFxQ2o3Ql9PUm5HSExROHNYS1h2ckNDQUlpNmxCemxJOEdBa1BIS0w3b0NpamdOaGFNUzNndGJ3d1QxWWJBMUVsNVBRdHVEM013NGV0cjJfRUt4dVR5SW9oems3cWlwSlZQSXRhd1VkWHNhMGpJR2M1YVBoeV8yMVVOWFdBTEM4YjFPSXdaWi1GNExrTnRLb0NzdlhMcGtQT3ctZWhmS0dyeHk5QmV1aWIxRDd4bjRmOVRDV1FMVE1BVnFhd201cmltX0h2b1lyOTBHS21iVmZjVmhWTXU1VW9lbnJDN3ZWOTBtdWxmSkRUWnFYZmF3OE9jTzEyU0pHWkpnTzdKMnA3WVFOdVBBclZsTnpuNzA3Qk5RcU91eUprNHNKV2dHRk92NlluYm9LaFdPQlV1NTFLSml2c3Bwc3FJcWQxTW5sUFZLZFZSUldOZWo0M3BPS2F4ZlA0dHhrUVFEX1JVR2p4bURuYzdnZEh1eXd1SzFoUWtVZjl0Z0NXSjhQUWxlQ2kxVk8yTzJJRmtLN0RuOTd5bWVYNGtMcUU3WWNZRWZhUHFveUNPejlxYVVPMXVQRlB2akdQVVR1QVVyVjFsVW5WcmtvbkFpN195OC1IaTk0UjQycGlwcVRCWjdGODhIQmFidXNIa3cwUWZmVFdfd09TRTRZQkx2RWN1WExKSUhMNUk3WlM5d3lYLXpHTTZjb1ZxOTdBRzZHQWFpYlVEVGhxeWNYWWJnaGxSUEJRcE9BeTNpWXZ0Ulc1VlhiUC1Da2xrM0RzTXBPU2o4ZF8tLWlBVzZ5TjMzU2lBY25PSFNBZ1JUQ21UUm9MQUVCNVNYdjJnUXZ6LVBRbEhfeEtBbVQ1RFNMTGtkUkNTNTg0QnlVQmdrdWRQYk5ERS1ncXJtR0lLV1JpTHc2LS1lVHpTRVFKbktfcFEzcnc1TzVDcXVuTEYzRDNQdXYtMW1WNHdKdmszNXFOcXBEMnRRTG55VmhxN1ZsQU4tVHFOS1ZUNVFvWTRqaFktMmdMYW5kdFUwb1JvSHJkRUN1ZklBNGswY0ZuYU1mTExiWUJqUkdhdmpBSUNQUW1fazVvUmtJMHBwam1fSEFRamVQSXJaV0FQYndqUVk2TExRWHFpQjRhUUlKZ2hrcjVwcF9Ka2FoTWI4bnZvZjNPenp5Z2hVTnVRS0hYVnhHYlZVb0x1TW9yX1QzSkxpeHNkSW5SS1BEbEM3ekhoQlRWb0VmbTRmRXdXMnFvd3YwQjY5RS1DaWdNSDlVZjZaTjBoU3BITmlIT2s1S0VYeXpFREtQeXVRVnFpa1NYRE56R1pYNmVNQ21LaDRzQk5Xc0FJQU44WVRKWnRiX0NXRnZ3T0VnSTcteVdLWUc3SXZQSlFHeGt3UWowanM4cnh5cTdnb2lDemFBbTYtNndYU1p6WFA1VmF2SjdubWhaQTlRa1hjN0tnTXZTeW94RG1RaVI4dGhmMnR3Mm5Mb1pEOFFLQ2JHX2lfUkktRHVaUGdpd1FrLVR0aW4zTGFVckx5Wm1rcWlmeUs0amZYTGJUakRweGw4WUpNeWpsSnZ5U1VqSzRrZ0twNjNhWlhza19nOC00UjI4Z1h2ekNFdm9CQmI5NFRldmRtOEtVUk9KNk9kZS1CN3haZGUtS0d5QzhGVXgyMFg5dTJiSEI4b1l2dE1IQmY2dS1QTEtyS001LVFNTnA3dWh1TFlsMHpMb2l2cDVrNkR0VW15dUNnbUFIZGJxZDJqMUNuZVRnUFROZVdpbEtfWjg0ODQ4RlNsMk5WaDI3c1JyeFFlc1lrSktQeFY5VnRCX1Z4Y2Q4Xy1FSE05V1BOQmIzcHpEczE3OVMxWGVaSEVyU0ZXV1Bfc19VeGFrTHJUZWRfcEY2bXN0ZzZzV2t1ZDJqQ2pQUENMX21DVld3TERoVFJOeU5hb1lWNjVMSmtkM0hUTE5FYnk3M2dnR3NhU0o4aE9lZnNsSGN4eGtiTmdOTDJEQUM4YzVmeFllZEozVmZRT3BnM0RHUFRqQVpnOXJWVWc1Rnd4clVZQ1dSYnhhNEY1YUVrSU9qTUxQVm95UXlxbEVza3FZbWJpZDhzb0dYQ1RQUGlabkhQUlNxQ0JObGFWUjFtSjN0OEhDZXRveHZxa1pFei10ZHhGTTZLWEMyNVVPOTBfWE84Q05wZ0tKd0c2UFMtQ3JuREVwSXdhWWUyMG5KdHJVdlVESk42bElsZlU0WVp5UEdaYzFkTHl6dFNtbTNwM1h2THpwaFJRZVItcDRIQ005NjZDcjZVNGc1eDRQTXdCaVhJcjRmNkpDREdlSEt1NHNiR0FBTmszcFhyWG1ZV1VheGx4djBMSUhnbUZDSWhQUW9HWDcxdHFnUldhMklzdXhGdk83RHNIMkQxY3NLQ01ta3puNmQtbkJlMVBlZG5xVWN1Q3k5OE92TGtETjlkT21zME5Qc1lBSVVaZXVMdW1ka3dWX1g1RU9rRGJFa2t3d1JMOHFCTkowbl9SOW9lQWlmQW0tRUFQZnp2WXpFaWJ3YUREZ2k0ejVRWHhFVGs0WGlfV3hQR3U5U3J1NjNqbVIyaklqa2ZwOThqeGgyUHhSTXNVeUx2b045cEE0T3hNYnktbmVfU1lDZGNOR25iMzV1a19FQXBxZ1czTjA2b3I5QUo0Z2JaczhwRzhfQTZEdjhIaFo5ZV83cERvcUh3ZWlKa3BpdGUtTHNESUpMWjlCQWs4TjQyTVdfN1lTc0QzM0E3cjlJRDV6bzI0bldzdUtsTXdBcDFDZHJ0d1VGYzlZc19mc1pacXJUMmNtTzB5VktXaVRHM0g0SUZTMjZuMmdpMU9lbzVPcWpLV3dXc3EwTmRDSlBGaWdhQW5HLWFmQVhra21UREVvTmMzMTd6QXloWkRGOG5nTDVhQUhTVVJfd1pKVFZiZEc5N1ZFNzI0dV9NS3FTVVVuaGhJYXhxd0dsREk0LU5KX3owS2ZmcmQzZW1UTmxGb2w2MWpCdW9TUEp3TUoweWJ4NHhzQl8xTTNLMHhqN1pwcXdPOHE1YVl0blVqYlJWVDFxMDVYeGczSXZROVJlUmtlZWdVZVZ0VzNZY2dDLVF2ZDR1bmtYLVJYX0cwTVJybjU2aDdvdVB4bXJONzNaRHk0UGR5Z2xZdzF2TG14V1NqeGR6V1lwaE9EV0JjaXh1YTd4eDkzV3B0bXVVYkZLTUhta1FSUGVnN2NWckZWTkNpWTEyZ09xMGNwOG5wdzA0dFRYM0xQRjFqQ3FqSUpHRHRmTkF0b0hTb1k3RUFxb3VjMjN0THEtTVBHTjd5SXdqWmY2QU96SExpRzcza2Z0Wk1oWnhwbmJBVVUwRTdqS0ZydGdfZFo3b2tUdEI3bkgxemd3VVc2aVQtcFl2VXlaOUhEMFNPWnZkLWRqMjZubUVucWdhS1pLc0JhZEk2QjZULTF5YzJwOFBoNTVxNzlCY3BjcFVlRnkySG9iN3hRTjNHNi1PSkFEdkdieEN5R2UtQU5DMWZPa0IwaFhwQmJRVFprLUFKOTNTYy1kelIxZUc1WVdPdFd6OEdQSTlIYThCTGd3NE16cGtFTVFuOU00THlveUxoR1ZSY0YtZERRRDlRcXc5WWtxRGozU2phTVZhOGptbXZYbEwzTndmeE9qUDRVMlcwUE1GOTA0aHJtZ0d5SFRPQktLLU9MNFo3UVlmQkF2TEdEaFdiZGNUczJDYllFMndZU2k3X29Ja3dWaVAzNkZPZnQzcGZCcVpiVTI2V2oxNlY5R3ZkNjYtUzRxeDJLOVBobDBod3p4LTZ1bmZ4eDhUaTNHNzc1UDNBX3JJM01hS2NZaS1fdDhzdFo0NmJSaFh6TWxJekNRLUdXMHEtdk0xR1MweEd6MTBOWWcxZktuUURwQVB1OUVvWm0zRHlmU2xmMUFKa1ZjVE9GWXVTSmoydGxYbXVYQk00aFJZQVVBeWE3OTRTWkZIanlTRlBSdzZtUnhrcnd0WVJ0Sm9sVHNBbVZjc24tU1FIdnZKN0dpenp3ODREa29TbFRTdERuV2R6dGpyY05DcW03SFhmdmlpcjdZSHd0aVIxdUNHQi1IczVRSGktUy03ZWtBdkNhM3VMUERiSU56VXJTUUMxeXBPZTNIdU1KQmRWUXZYYlJUTkJRdi1FWWV5bEVNRzRnLXlfaGxWX1ZiZG1SNy1TY0xjbDZXeDJqbF9GMTBLbXRpMnhfVEtkaFRUSkVLQUZ2dS01TUlBcWlmQjQ4RGhOLVlhMnlGTkhLamVnVFdVWHY3bHpVOWhaRWJCZFIyZ3o1UUJQYmxlWUUwSmszWjNUbmNuVFc3dE4wZ3Y4SnlCZ1FxU0pHQWNtOHdUbjRSZENzM1J5U2Z1LW5zWWVJdWxhcDlNUXR6VkVtV18yNndnbUI5cVVQX3Q5QTN6SjlJc01PdWpTOU9VRm03clkzLU1tY25RMS1LOUpYX1hfY3VfcHY4Nk1MalRuZmhpT1JERERRSzRPZ2hIYWhQb0R0QmJodnA1WkJKaTQyWFF3X0dhNmZLUW9VaEFtT0Q4WFZ0bEV2d0V5NE1hMktSZUhZU09NR1ZzaTFsa19hTXVvWHdGWER2cTNnamV0MWctdTNmUGNEOV96YzZYOHFQaGN1N2xZSGNLUDdjNE5ESkcwWFgyV1ZmSnUxWXZXUUhHcDh3S3dOQXJpRkx2UEhWRHNFVGtnRzBPVmwwendoejlDNi1hRThFbTNNemFselRqanFwVmFOcTdpNVZncGhubi01bW95SlY2LS1XZmx3aVF0cW9ldEJMWnlncnJHUTQ2dVRaTlNoSkxhZmIwaEZfVXBCMEpoY1ZUOUFlb0lXMHN1dHZ6QVRDcmZXOHJLbEdFVWJ1dHd5V1ZIZzE0emhwVGF4TnpfQlFyMHZvX1NtSUhseFcxUmw2UUo3WjRqaFVVaEktdXdpd3J0dmkyc0FNeW5IZUxwaE5id2JhYUw3WXlxUk9kbVZKazhDbTFpTTZKTHVhbUl5dzBoeWQzUW9oM3BMbUdRWEJQODh1akZyMDNnbHFkWV83aXRsZFFpNGV6Y0F0blhCVmhZUnExR0dtN2ZiUjlXZXp3ZjRmdVpQRmtLb01mRURkb0ZhT1FSVjl6UFhoVEU0UFB2U0hSQ1NXOVVUSXpWRWl3TlRqSEVRRUFfaUswMGVtQmw5ZVNCQVMyYm1neXBTS085ak9mSHJNUFJySldhNFpHMXhpeFdCVEx1TnhQeXlxRW9rbjNMMGhRZW1GT2FZc21jR25QWFE0RT0=) # <-- Put your encrypted keystore file here
        KEYSTORE_PATH: '/tmp/keystore.keystore'
        KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmcwZEJLcVJlLWhxR3o1NEVYSUJBZjc0WE05S285ejNqbjU3SFJhaWpTX0xYQVAxN2hXUFV0aTFpdVpsY0lXa2Fsd2VUX1hKeDktVlRqeTNsVHlScXZvUWNocnc9PQ==) # <-- Put your encrypted keystore password here
        KEY_ALIAS_PASSWORD: Encrypted(Z0FBQUFBQmcwZEJLcVJlLWhxR3o1NEVYSUJBZjc0WE05S285ejNqbjU3SFJhaWpTX0xYQVAxN2hXUFV0aTFpdVpsY0lXa2Fsd2VUX1hKeDktVlRqeTNsVHlScXZvUWNocnc9PQ==) # <-- Put your encrypted keystore alias password here
        KEY_ALIAS: Encrypted(Z0FBQUFBQmcwZHA2UnQzanJIV3dVVFhjMThlbGhBNXR5ZnUzYjBLcDdsOEczYmRpOTVWNERtaU1aZFR6c3A1a1RXcFpwXy1ZMEk4U3Y0Mkx5NURHRWctNnpuNXhJbGJGRUE9PQ==) # <-- Put your encrypted alias password here
      xcode: 12.4
      node: 12
      npm: 6

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'release-*'
          include: true
    # cache:
    #   cache_paths:
    #     - $FCI_BUILD_DIR/node_modules

#     triggering:
#       events:
#         - tag
#       tag_patterns:
#         - pattern: 'release-*'
#           include: false
#     cache:
#       cache_paths:
#         - $FCI_BUILD_DIR/node_modules

    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm ci
          cvm install 9.0.0
          cvm use 9.0.0   
          echo $BUILD_NUMBER
      - name: Add Android platform
        script: |
          set -x
          cordova platform remove android --nosave
          cordova platform add android --confirm --no-interactive --noresources          
      - name: Build Android
        script: |
          set -x
          set -e
          cordova build android --release --no-interactive --prod --device
          echo $KEYSTORE | base64 --decode > $KEYSTORE_PATH
          UNSIGNED_APK_PATH=$(find platforms/android/app/build/outputs -name "*.apk" | head -1)
          jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore "${KEYSTORE_PATH}" -storepass "${KEYSTORE_PASSWORD}" -keypass "${KEY_ALIAS_PASSWORD}" "${UNSIGNED_APK_PATH}" "${KEY_ALIAS}"
          mv $UNSIGNED_APK_PATH $(echo $UNSIGNED_APK_PATH | sed 's/-unsigned//')          
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
      - platforms/android/app/build/outputs/**/mapping.txt
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - nihal@nevercode.io
      slack:
        channel: '#test_channel'
#       scripts:
#         - name: App Center
#           script: |
#             echo 'Installing App Center CLI tools'
#             npm install -g appcenter-cli
#             echo "Find build artifacts"
#             apkPath=platforms/android/app/build/outputs/apk/release/app-release.apk
#             echo "Found apk at $apkPath"

#             if [[ -z ${apkPath} ]]
#             then
#                 echo "No apks were found, skip publishing to App Center"
#             else
#                 echo "Publishing $apkPath to App Center"
#                 appcenter distribute release \
#                     --group Collaborators \
#                     --file "${apkPath}" \
#                     --release-notes 'App submission via Codemagic' \
#                     --app nihalagazade/io.cordova.hellocordova \
#                     --token df84dfdec4301fc5feccdc7a9c6545a93db24d93 \
#                     --quiet
#             fi
